services:
  - type: web
    name: rag-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OLLAMA_BASE_URL
        value: http://host.docker.internal:11434
      - key: OPENAI_API_KEY
        value: your-api-key-if-used
    region: oregon
    plan: free
